services:
  app:
    build: .
    container_name: community-app
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET}
      - JWT_EXPIRATION=36000000
      - JWT_REFRESH_EXPIRATION=604800000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/communitydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: ./mvnw spring-boot:run
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=communitydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./files:/files

volumes:
  postgres_data: