spring.application.name=communitydb
spring.datasource.url=jdbc:postgresql://localhost:5432/communitydb
spring.datasource.username=postgres
spring.datasource.password=chanquete94

spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update